#!/usr/bin/env bash
# make-media-fixture-tree.sh —— 媒体库 fixture 树的幂等生成器。
#
# 产物：.planning/spike/media-fixture/ —— 结构与 MediaFixtureTree 单测 helper
# 逐项一致：多子目录、三层深嵌套、混合扩展名、空目录、无权限目录、
# 中文+空格目录名、根外符号链接、Converted/ 与 converted-lower/ 并存各一半。
#
# 三条纪律：
#   * 整棵树可 `rm -rf` 后重建（判据连跑两次验证幂等）。真实素材只建符号链接，
#     不把 GB 级素材复制进仓库 —— 本脚本没有整词的复制命令（判据剥注释后
#     `\bcp\b` 计数 == 0 机械保证）。
#   * 树里几类"伪视频"（broken.mp4 的 ASCII 文本 / notes.txt / mkv-avi-webm
#     占位）让扫描器有实体可查。
#   * 不触碰真实素材目录：本脚本对真实目录零调用。
#
# 可播放种子：脚本内嵌一段 0.5s 48x48 Motion-JPEG 小视频（base64），让 tracer
# 在 fixtures/ 缺席时也有真实可加载的视频轨。这**不是** ffmpeg，也不是转码测试
# —— 只是让树的"视频文件"真的可播，AVPlayerLooper 才能入队出 3 个条目。

set -u
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MEDIA_ROOT="$ROOT/.planning/spike/media-fixture"
TMP_ROOT="${TMPDIR:-/tmp}"
OUTSIDE_ROOT="$TMP_ROOT/pic-outside-$$"
FIXTURES="$ROOT/fixtures"

alarm() { perl -e "alarm $1; exec @ARGV" "${@:2}"; }

# 幂等性的前提：先整体删再整体建。
rm -rf "$OUTSIDE_ROOT"
rm -rf "$MEDIA_ROOT"
mkdir -p "$MEDIA_ROOT/sub/deep/deeper" \
         "$MEDIA_ROOT/Converted" \
         "$MEDIA_ROOT/converted-lower" \
         "$MEDIA_ROOT/视频壁纸" \
         "$MEDIA_ROOT/empty" \
         "$MEDIA_ROOT/noperm" \
         "$OUTSIDE_ROOT"

# 树外目标（link-out.mp4 的符号链接落点）。fixtures/ 缺席时给占位内容，
# 树的结构不依赖它；在场时才放 clip-a 的符号链接。
MEDIA=absent
if [ -f "$FIXTURES/clip-a.mp4" ]; then
  MEDIA=present
  ln -sfn "$FIXTURES/clip-a.mp4" "$OUTSIDE_ROOT/secret.mp4"
else
  printf '%s\n' "seed outside secret" > "$OUTSIDE_ROOT/secret.mp4"
fi

# 七个"视频"文件：普通文件（可播放的内嵌种子）。为什么不是符号链接？
# 扫描器的 resourceValues 层把符号链接一律排除（isRegularFile==false 且
# isSymbolicLink==true），若这些文件是符号链接，tracer 将拿不到任何条目，
# MEDIA_TRACER_PLAN=playing 永远到不了。
VIDEO_B64='AAAAFGZ0eXBxdCAgAAAAAHF0ICAAAAAId2lkZQAADsxtZGF0/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z/9j/2wCEABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2MBERISGBUYLxoaL2NCOEJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY//AABEIADAAMAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AOdooor0zzgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/ZAAAC221vb3YAAABsbXZoZAAAAADm5oRh5uaEYQAAAlgAAAJYAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAJndHJhawAAAFx0a2hkAAAAD+bmhGHm5oRhAAAAAQAAAAAAAAJYAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAwAAAAMAAAAAAARHRhcHQAAAAUY2xlZgAAAAAAMAAAADAAAAAAABRwcm9mAAAAAAAwAAAAMAAAAAAAFGVub2YAAAAAADAAAAAwAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAJYAAAAAAABAAAAAAGbbWRpYQAAACBtZGhkAAAAAObmhGHm5oRhAAACWAAAAlhVxAAAAAAAMWhkbHIAAAAAbWhscnZpZGVhcHBsAAAAAAAAAAAQQ29yZSBNZWRpYSBWaWRlbwAAAUJtaW5mAAAAFHZtaGQAAAABAECAAIAAgAAAAAA4aGRscgAAAABkaGxyYWxpc2FwcGwAAAAAAAAAABdDb3JlIE1lZGlhIERhdGEgSGFuZGxlcgAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAxhbGlzAAAAAQAAAMpzdGJsAAAAZnN0c2QAAAAAAAAAAQAAAFZqcGVnAAAAAAAAAAEAAAAAAAAAAAAAAgAAAAIAADAAMABIAAAASAAAAAAAAAABBidqcGVnJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAGHN0dHMAAAAAAAAAAQAAAAYAAABkAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAGAAAAAQAAABRzdHN6AAAAAAAAAnYAAAAGAAAAFHN0Y28AAAAAAAAAAQAAACQ='

for v in a.mp4 B.MOV sub/c.m4v sub/deep/deeper/d.MP4 Converted/out.mp4 converted-lower/keep.mp4 视频壁纸/e.mp4; do
  printf '%s' "$VIDEO_B64" | base64 -D > "$MEDIA_ROOT/$v"
done

# 几字节的占位文件。broken.mp4 必须是 ASCII 文本（真跑 AVFoundationAssetProbe
# 时它解不出视频轨，这正是要的）。
printf 'plain text, not a video\n' > "$MEDIA_ROOT/notes.txt"
printf 'this claims to be a video but has no video track\n' > "$MEDIA_ROOT/broken.mp4"
printf 'mkv placeholder, not natively playable\n' > "$MEDIA_ROOT/sub/skip.mkv"
printf 'avi placeholder, not natively playable\n' > "$MEDIA_ROOT/sub/y.avi"
printf 'webm placeholder, not natively playable\n' > "$MEDIA_ROOT/sub/z.webm"

# 根外符号链接：link-out.mp4 -> <临时>/pic-outside-<pid>/secret.mp4（根外）。
ln -sfn "$OUTSIDE_ROOT/secret.mp4" "$MEDIA_ROOT/link-out.mp4"

# 无权限目录：先 000 再复原。复原必须在退出前 —— 否则下一次 `rm -rf` 会失败，
# 且这棵树会变成一个谁都不敢碰的目录。
printf 'hidden, never scanned anyway\n' > "$MEDIA_ROOT/noperm/hidden.mp4"
chmod 000 "$MEDIA_ROOT/noperm"
printf 'MEDIA_TREE_NOPERM_MODE=000\n'
chmod 755 "$MEDIA_ROOT/noperm"

FILES=$(find "$MEDIA_ROOT" \( -type f -o -type l \) 2>/dev/null | wc -l | tr -d ' ')

printf 'MEDIA_TREE_ROOT=%s\n' "$MEDIA_ROOT"
printf 'MEDIA_TREE_FILES=%s\n' "$FILES"
printf 'MEDIA_TREE_MEDIA=%s\n' "$MEDIA"

if [ "$MEDIA" = "absent" ]; then
  printf '%s\n' "hint: run scripts/make-fixtures.sh (ffmpeg lavfi seed clips) then re-run this script to switch MEDIA=present" >&2
fi

exit 0